// Copyright 2023 Travis Mick (@tmick0)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once
#define TAPPING_TERM 200
#define LT_TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLDS
#define TAP_CODE_DELAY 20

#define MASTER_RIGHT

#define PIMORONI_TRACKBALL_ADDRESS 0x0A
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define POINTING_DEVICE_ROTATION_90

#define MOUSE_CPI 24000
#define SCROLL_CPI 2000

#define AUTO_MOUSE_THRESHOLD 0
#define AUTO_MOUSE_TIME 1200
